spring.application.name=sb-ecom

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#set(update)to update only the changes in the schema/table
#spring.jpa.hibernate.ddl-auto=update

#url=jdbc:h2:mem:a7f8a5d4-9369-436c-819c-c6e8ef947777